### ISSUE TITLE
Chrome Webstore?

### ISSUE THREAD

**Issue by orschiro** [sasindumendis/remarkable-googlekeep#1]
Dear @sasindumendis,

I found your great extension [here](https://webapps.stackexchange.com/questions/88955/markdown-formatting-in-google-keep?noredirect=1#comment82527_88955).

Thank you!

Do you have any plans to add this extension to the Chrome Webstore?

Thankfully,

~Robert

**Comment by sasindumendis** [comment]
@orschiro Glad to hear you found it useful!

TBH this was a little experiment to see if I can rely on Google Keep for note taking as a power user. Therefore didn't really have plans to add it to Webstore nor I saw enough interest from others to do so.

BTW thank you for pointing where you found it 😄

**Comment by orschiro** [comment]
Alright, get your point. 

Thanks for your quick response! :smiley: 

~Robert
