### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by emil-nasso** [sasindumendis/remarkable-googlekeep#5]
I couldn't install the extension the way it was described in the instructions.

I downloaded the crx-file and dragged it to chrome. Got this error message:

![https://dl.dropboxusercontent.com/s/d8si8ndn9m2h398/2016-08-09%20at%2011.12.png](https://dl.dropboxusercontent.com/s/d8si8ndn9m2h398/2016-08-09%20at%2011.12.png)

This message links here: https://support.google.com/chrome_webstore/answer/2664769?p=crx_warning&rd=1

Is there any way to get around this and install the extension?

**Comment by sasindumendis** [comment]
You can download the source (zip archive) instead and install it like so:
1. Open Chrome and go to **More tools > Extensions**.
2. Make sure **Developer mode** is checked.
3. Click **Load unpacked extension** and select the **src** directory from extracted source archive downloaded before.
4. Now enable the extension loaded.
